# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20180323_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
